const mongoose = require("mongoose");
require("dotenv").config();

const Route = require("./models/Route");

const routes = [
  {
    pickup: "Charbagh",
    destination: "Kaiserbagh",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Kaiserbagh",
    destination: "Chowk",
    fare: "₹10-15",
    distance: "2-3 km",
    time: "10-15 min",
  },
  {
    pickup: "Aminabad",
    destination: "Chowk",
    fare: "₹10-15",
    distance: "2 km",
    time: "10-12 min",
  },
  {
    pickup: "Hazratganj",
    destination: "Aminabad",
    fare: "₹10-20",
    distance: "2-3 km",
    time: "10-15 min",
  },
  {
    pickup: "Hazratganj",
    destination: "Gomti Nagar",
    fare: "₹20-30",
    distance: "6-8 km",
    time: "20-30 min",
  },
  {
    pickup: "Gomti Nagar",
    destination: "Polytechnic",
    fare: "₹15-25",
    distance: "5-6 km",
    time: "15-25 min",
  },
  {
    pickup: "Polytechnic",
    destination: "Engineering College",
    fare: "₹10-15",
    distance: "3-4 km",
    time: "10-15 min",
  },
  {
    pickup: "Engineering College",
    destination: "Munshi Pulia",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Munshi Pulia",
    destination: "Indira Nagar",
    fare: "₹5-10",
    distance: "1-2 km",
    time: "5-10 min",
  },
  {
    pickup: "Indira Nagar",
    destination: "Bhoothnath Market",
    fare: "₹5-10",
    distance: "1-2 km",
    time: "5-10 min",
  },
  {
    pickup: "Indira Nagar",
    destination: "Polytechnic",
    fare: "₹10-20",
    distance: "3-4 km",
    time: "8-15 min",
  },
  {
    pickup: "Nishatganj",
    destination: "Hazratganj",
    fare: "₹10-20",
    distance: "4-5 km",
    time: "15-20 min",
  },
  {
    pickup: "Nishatganj",
    destination: "IT College",
    fare: "₹5-10",
    distance: "1-2 km",
    time: "5-10 min",
  },
  {
    pickup: "Kapoorthala",
    destination: "Aliganj",
    fare: "₹10-15",
    distance: "2-3 km",
    time: "10-15 min",
  },
  {
    pickup: "Aliganj",
    destination: "Engineering College",
    fare: "₹10-15",
    distance: "3-4 km",
    time: "10-15 min",
  },
  {
    pickup: "Polytechnic",
    destination: "BBD",
    fare: "₹20-30",
    distance: "6-8 km",
    time: "15-25 min",
  },
  {
    pickup: "BBD",
    destination: "Kamta",
    fare: "₹10-20",
    distance: "6 km",
    time: "10-15 min",
  },
  {
    pickup: "BBD",
    destination: "Matiyari",
    fare: "₹5-10",
    distance: "2-3 km",
    time: "5-10 min",
  },
  {
    pickup: "BBD",
    destination: "1090 Chauraha",
    fare: "₹20-30",
    distance: "7-9 km",
    time: "20-30 min",
  },
  {
    pickup: "BBD",
    destination: "Hazratganj",
    fare: "₹30-40",
    distance: "12-14 km",
    time: "30-45 min",
  },
  {
    pickup: "BBD",
    destination: "Barabanki",
    fare: "₹30-40",
    distance: "20-22 km",
    time: "35-50 min",
  },
  {
    pickup: "Alambagh",
    destination: "Airport",
    fare: "₹20-30",
    distance: "5-6 km",
    time: "15-20 min",
  },
  {
    pickup: "Charbagh",
    destination: "Airport",
    fare: "₹30-40",
    distance: "10-12 km",
    time: "25-35 min",
  },
  {
    pickup: "Alambagh",
    destination: "Charbagh",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Alambagh",
    destination: "Kaiserbagh",
    fare: "₹15-20",
    distance: "5 km",
    time: "15-20 min",
  },
  {
    pickup: "Charbagh",
    destination: "Hazratganj",
    fare: "₹15-20",
    distance: "5 km",
    time: "15-20 min",
  },
  {
    pickup: "Charbagh",
    destination: "Aminabad",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Hazratganj",
    destination: "Nishatganj",
    fare: "₹10-20",
    distance: "4-5 km",
    time: "15-20 min",
  },
  {
    pickup: "Hazratganj",
    destination: "Aliganj",
    fare: "₹20-30",
    distance: "7 km",
    time: "20-30 min",
  },
  {
    pickup: "Nishatganj",
    destination: "Aliganj",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Munshi Pulia",
    destination: "Gomti Nagar",
    fare: "₹15-20",
    distance: "5 km",
    time: "15-20 min",
  },
  {
    pickup: "Gomti Nagar",
    destination: "1090 Chauraha",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Kamta",
    destination: "Polytechnic",
    fare: "₹15-25",
    distance: "6 km",
    time: "15-25 min",
  },
  {
    pickup: "Chinhat",
    destination: "Kamta",
    fare: "₹10-15",
    distance: "4 km",
    time: "10-15 min",
  },
  {
    pickup: "Chinhat",
    destination: "Gomti Nagar",
    fare: "₹20-25",
    distance: "7 km",
    time: "20-25 min",
  },
  {
    pickup: "Barabanki",
    destination: "Chinhat",
    fare: "₹30-40",
    distance: "20 km",
    time: "35-50 min",
  },
  {
    pickup: "IT College",
    destination: "Kapoorthala",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Aliganj",
    destination: "Bhoothnath",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Polytechnic",
    destination: "Nishatganj",
    fare: "₹10-15",
    distance: "3 km",
    time: "10-15 min",
  },
  {
    pickup: "Kamta",
    destination: "Matiyari",
    fare: "₹15-20",
    distance: "5.1 km",
    time: "15-16 min",
  },
  {
    pickup: "Rumi Gate",
    destination: "Saadatganj",
    fare: "₹10-20",
    distance: "5.8 km",
    time: "19-20 min",
  },
  {
    pickup: "Rajajipuram",
    destination: "Polytechnic",
    fare: "₹40-50",
    distance: "15 km",
    time: "41-50 min",
  },
  {
    pickup: "Rajajipuram",
    destination: "Alambagh",
    fare: "₹15-20",
    distance: "5.1 km",
    time: "13-15 min",
  },
  {
    pickup: "Hussainganj",
    destination: "IT College",
    fare: "₹10-15",
    distance: "5.2 km",
    time: "19-20 min",
  },
  {
    pickup: "Amausi",
    destination: "Polytechnic",
    fare: "₹40-50",
    distance: "25 km",
    time: "36-40 min",
  },
  {
    pickup: "Amausi",
    destination: "Alambagh",
    fare: "₹20-25",
    distance: "5.4 km",
    time: "14-20 min",
  },
  {
    pickup: "Rajajipuram",
    destination: "Ashiyana",
    fare: "₹30-35",
    distance: "10 km",
    time: "29-32 min",
  },
  {
    pickup: "Kaiserbagh",
    destination: "Cantt",
    fare: "₹15-20",
    distance: "4.7 km",
    time: "17-20 min",
  },
  {
    pickup: "Butler Palace",
    destination: "KGMU",
    fare: "₹20-25",
    distance: "5.5 km",
    time: "16-20 min",
  },
  {
    pickup: "Dubagga",
    destination: "Kapoorthala",
    fare: "₹40-50",
    distance: "14 km",
    time: "33-35 min",
  },
  {
    pickup: "Butler Palace",
    destination: "Cantt",
    fare: "₹15-20",
    distance: "4.4 km",
    time: "11-15 min",
  },
  {
    pickup: "Telibagh",
    destination: "Alambagh",
    fare: "₹20-30",
    distance: "9 km",
    time: "20-25 min",
  },
  {
    pickup: "Telibagh",
    destination: "Hussainganj",
    fare: "₹20-30",
    distance: "9 km",
    time: "20-25 min",
  },
  {
    pickup: "1090 Chauraha",
    destination: "Transport Nagar",
    fare: "₹30-40",
    distance: "17 km",
    time: "35-45 min",
  },
  {
    pickup: "Faizabad Road",
    destination: "Cantt",
    fare: "₹40-50",
    distance: "16 km",
    time: "33-40 min",
  },
  {
    pickup: "Chinhat",
    destination: "Chowk",
    fare: "₹35-45",
    distance: "12 km",
    time: "25-30 min",
  },
  {
    pickup: "Thakurganj",
    destination: "Hazratganj",
    fare: "₹15-25",
    distance: "7 km",
    time: "20-25 min",
  },
  {
    pickup: "PGI",
    destination: "1090 Chauraha",
    fare: "₹30-40",
    distance: "12 km",
    time: "25-30 min",
  },
  {
    pickup: "Indira Nagar",
    destination: "Munshi Pulia",
    fare: "₹10-15",
    distance: "2 km",
    time: "3-5 min",
  },
  {
    pickup: "Cantt",
    destination: "Balaganj",
    fare: "₹30-40",
    distance: "11 km",
    time: "35-40 min",
  },
  {
    pickup: "IT College",
    destination: "Aliganj",
    fare: "₹10-20",
    distance: "5 km",
    time: "10-15 min",
  },
  {
    pickup: "Mahanagar",
    destination: "Ashiyana",
    fare: "₹40-50",
    distance: "15 km",
    time: "30-35 min",
  },
  {
    pickup: "Rumi Gate",
    destination: "SGPGI",
    fare: "₹45-55",
    distance: "17 km",
    time: "40-50 min",
  },
  {
    pickup: "Balaganj",
    destination: "LDA Colony",
    fare: "₹25-35",
    distance: "13 km",
    time: "30-35 min",
  },
  {
    pickup: "Bhoothnath",
    destination: "Hussainganj",
    fare: "₹10-20",
    distance: "8 km",
    time: "20-25 min",
  },
  {
    pickup: "Badshah Nagar",
    destination: "Kaiserbagh",
    fare: "₹10-20",
    distance: "6 km",
    time: "15-20 min",
  },
  {
    pickup: "Transport Nagar",
    destination: "Chinhat",
    fare: "₹40-55",
    distance: "24 km",
    time: "40-50 min",
  },
  {
    pickup: "Rajajipuram",
    destination: "Kamta",
    fare: "₹55-65",
    distance: "20 km",
    time: "40-50 min",
  },
  {
    pickup: "Badshah Nagar",
    destination: "Hussainganj",
    fare: "₹20-25",
    distance: "6 km",
    time: "15-20 min",
  },
  {
    pickup: "Badshah Nagar",
    destination: "kamta",
    fare: "₹20-25",
    distance: "7 km",
    time: "15-20 min",
  },
  {
    pickup: "Rajajipuram",
    destination: "Polytechnic",
    fare: "₹40-50",
    distance: "16 km",
    time: "35-40 min",
  },
  {
    pickup: "Telibagh",
    destination: "Rumi Gate",
    fare: "₹30-40",
    distance: "13.5 km",
    time: "30-35 min",
  },
  {
    pickup: "KGMU",
    destination: "Cantt",
    fare: "₹20-30",
    distance: "8 km",
    time: "15-20 min",
  },
  {
    pickup: "Jankipuram",
    destination: "Vikas Nagar",
    fare: "₹10-20",
    distance: "5.5 km",
    time: "10-15 min",
  },
  {
    pickup: "Chinhat",
    destination: "Transport Nagar",
    fare: "₹40-55",
    distance: "24 km",
    time: "40-50 min",
  },
  {
    pickup: "Chinhat",
    destination: "Para",
    fare: "₹35-45",
    distance: "15 km",
    time: "30-32 min",
  },
  {
    pickup: "Sadar",
    destination: "Barabanki",
    fare: "₹60-80",
    distance: "25 km",
    time: "40-50 min",
  },
  {
    pickup: "Alambagh",
    destination: "Munshi Pulia",
    fare: "₹40-55",
    distance: "17 km",
    time: "30-40 min",
  },
  {
    pickup: "Krishna Nagar",
    destination: "IT College",
    fare: "₹30-40",
    distance: "14 km",
    time: "30-40 min",
  },
  {
    pickup: "Thakurganj",
    destination: "Malhaur",
    fare: "₹55-65",
    distance: "19 km",
    time: "50-55 min",
  },
  {
    pickup: "BBD",
    destination: "Safedabad",
    fare: "₹10-20",
    distance: "9 km",
    time: "15-20 min",
  },
  {
    pickup: "BBD",
    destination: "Charbagh",
    fare: "₹50-60",
    distance: "18.2 km",
    time: "37-50 min",
  },
];

const seedRoutes = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
        serverSelectionTimeoutMS: 30000,
        connectTimeoutMS: 30000,
      });

    console.log("MongoDB Connected");

    await Route.deleteMany({});

    console.log("Old routes deleted");

    await Route.insertMany(
      routes.map((route) => ({
        ...route,
        vehicleType: "Shared Auto",
        city: "Lucknow",
        isVerified: true,
      }))
    );

    console.log(`${routes.length} routes inserted successfully`);

    await mongoose.connection.close();

    console.log("MongoDB connection closed");

    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
};

seedRoutes();